version: "2"
services:
    python_code:
        build:
            context: .
            dockerfile: dockerfile-python
        ports:
            - 5000
        networks: 
            - front-tier
            - back-tier
        links:
            - mysql_db
            - redis_cache

    mysql_db:
        container_name: "mysql_db"
        build:
            context: .
            dockerfile: dockerfile-mysql
        ports:
            - 6000:3306
        networks:
            - back-tier
        env_file: mysql_env
        volumes:
            - /storage/docker/mysql-datadir:/var/lib/mysql

    lb:
        image: dockercloud/haproxy
        ports:
            - 8080:80
        networks: 
            - front-tier
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock 
        links:
            - python_code

    redis_cache:
        container_name: "redis_cache"
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - back-tier

networks:
    front-tier: 
        driver: bridge
    back-tier:
        driver: bridge
